Resources:
  Scraping:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-scraping
      VisibilityTimeout: 1500
      RedrivePolicy:
        deadLetterTargetArn:
          "Fn::GetAtt":
            - ScrapingDLQ
            - Arn
        maxReceiveCount: 5
